add new tests
TimothyHuxx/jScript_group_test pull request #25
Opened 2022-10-21 02:31 UTC by AnnaIurchyk

Hello, Team!

2022-10-21 02:41 UTC, TimothyHuxx requested changes
the conflict must be resolved first

2022-10-21 03:12 UTC, TimothyHuxx requested changes
You need to update your local main. Then merge changes into your local branch (git merge main) then resolve the conflict. Then push to your remote branch (git push). Then request for review.

2022-10-22 03:35 UTC, Anakondos approved these changes
Approved

2022-10-22 05:15 UTC, OlgaAutomation4 approved these changes

2022-10-26 03:34 UTC, closed without merging