add new function
TimothyHuxx/jScript_group_test pull request #38
Opened 2022-10-22 19:31 UTC by Anakondos

charToASSCIICode function

2022-10-22 19:32 UTC, Anakondos commented
Please review, I have some issues with tests

2022-10-24 01:30 UTC, TimothyHuxx requested changes
Use "eql" instead of "equal" when working with type Object

2022-10-24 04:13 UTC, TimothyHuxx approved these changes
Approved

2022-10-24 04:13 UTC, adiuzhikov approved these changes
Approve

2022-10-24 04:14 UTC, merged